### ISSUE TITLE
Feature request: `isLowercase`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#10]
Checks whether the input is a string containing only lowercase characters.

**Example usage**

```javascript
import isLowercase from '@plexis/is-lowercase';

isLowercase('foo');
// => true

isLowercase('foo bar');
// => true

isLowercase('foo bar');
// => true

isLowercase('Bar');
// => false
```

**Comment by humanolaranja** [comment]
I'd like to try this one

**Comment by vorillaz** [comment]
@humanolaranja Sure thing, if you have any questions you can always ping me personally or run through our contribution.

**Comment by humanolaranja** [comment]
Done in #24, thanks =D
