### ISSUE TITLE
Feature request: `endsWith`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#13]
Checks whether the input text ends with the given pattern.

```javascript
  @param {String} text
  @param {String|Regex} pattern
  @param {Number} startingPosition, optional
```

**Example usage**

```javascript
import endsWith from '@plexis/ends-with';

const txt = 'This is me';

endsWith(txt, 'is me');
// => true

endsWith(txt, 'is m', txt.length - 1);
// => true

endsWith(txt, 'is m', txt.length);
// => false

endsWith(txt, 'Foo');
// => false
```

**Comment by felipebrunetti94** [comment]
hey there can i take it ?

**Comment by vorillaz** [comment]
@felipebrunetti94 Thanks for contributing, go for it!

**Comment by felipebrunetti94** [comment]
tks @vorillaz  :D

**Comment by felipebrunetti94** [comment]
sorry, but could you help me with the setup ? When I use "lerna create @plexis/ends-with" it just return "Invalid lerna command: create"

**Comment by felipebrunetti94** [comment]
Another question, may I do as much issues as I want or is just one for dev ? kk

**Comment by vorillaz** [comment]
@felipebrunetti94 Just use `lerna create ends-with` and it will place the new package inside the `/packages/` folder.
There is a template available for new packages (https://github.com/plexis-js/plexis/tree/master/.package-template)

Finally, you can do as many issues as you want.
