### ISSUE TITLE
Feature request: `toPascalCase / classify`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#16]
Converts the input text to [pascal case](http://wiki.c2.com/?PascalCase).

**Example usage**

```javascript
import toPascalCase from '@plexis/to-pascal-case';

toPascalCase('Cool');
// => 'Cool'

toPascalCase('cool mate');
// => 'CoolMate'

toPascalCase('Hey how are you today?');
// => 'HeyHowAreYouToday'

toPascalCase('camelCase');
// => 'CamelCase'

toPascalCase('kebab-case');
// => KebabCase

```

**Aliases**

```javascript
import toPascalCase from '@plexis/to-pascal-case';
import {toPascalCase, classify} from 'plexis';
```

**Comment by jack-chapman** [comment]
I'm happy to take this one on!

**Comment by vorillaz** [comment]
@jack-chapman Go for it and thanks for your contribution.

**Comment by jack-chapman** [comment]
I've got this working pretty well, but I'm struggling on the case in the example above:

`toPascalCase('camelCase'); // => 'CamelCase'`

I haven't figured out how to tell if the given string is camelcase or not.

Currently it will do this: `toPascalCase('camelCase'; // => 'Camelcase'`, as it treats all inputs the same.

A more specific `camelToPascal()` and `pascalToCamel()` functions might be better than having the `toPascalCase` function behave differently to normal when a camelcase input is supplied.

**Comment by vorillaz** [comment]
@jack-chapman I don't think you should I would go this way in simple steps:
- Trim the text.
- Use a regular expression that matches everything that's not alphadigital one or more times and the following character e.g 
`'hello world' => it will match ' ' as $1 and 'w' as $2`
`'hello --world' => it will match ' --' as $1 and 'w' as $2` etc

- Replace the first group with '' and uppercase the second one 
The implementation described above is toCamelCase #14

If you combine toCamelCase along with [toTitle](https://github.com/plexis-js/plexis/tree/master/packages/toTitle) you can create the desired result.

**Comment by vorillaz** [comment]
@jack-chapman Another approach would be.
- Use `'text'.split()` along with a regular expression that matches non-numerical characters
- Iterate the array and uppercase the first letter of each word using [toTitle](https://github.com/plexis-js/plexis/tree/master/packages/toTitle)
- Join the array using `[].join()` 

You have implemented camelize again :D
- Use `toTitle` once more for the first character of the output .

**Comment by vorillaz** [comment]
@jack-chapman One way or another you can start working with `toCamelCase` or wait someone's merging their PR, eventually you can create the desired example using a combination of these two packages. Does this approach make sense to you?

**Comment by jpbelo** [comment]
If @jack-chapman decides to drop this I can pick it. 
It would be my first open-source contribution ever but I think I can do it properly. Let me know.

**Comment by jack-chapman** [comment]
@vorillaz Thanks for the input and recommendations. I'll continue this later on tonight and hopefully raise a Pull Request for you 👍
