### ISSUE TITLE
Feature request: `isEmpty`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#19]
Checks whether the input text is empty.

**Example usage**

```javascript
import isEmpty from '@plexis/is-empty';

isEmpty('');
// => true

isEmpty('   ');
// => true


isEmpty(' b  ');
// => false

```

**Aliases**

```javascript
import isEmpty from '@plexis/is-empty';
import {isEmpty} from 'plexis';
```

**Comment by eElec** [comment]
Hi, I was working on this and I created a package that works. However `packages/plexis/test/index.js` test is not passing and I am not sure how to fix this. I am pretty new to this, would be helpful if I knew what was going on. Thanks.
![Screenshot from 2019-10-21 02-31-33](https://user-images.githubusercontent.com/25086429/67166254-4f7c1580-f3ab-11e9-98f5-6e3914925d7b.png)

**Comment by eElec** [comment]
Hi, I was working on this and created a package that works as described. However I am facing a problem where `packages/plexis/test/index.js` test cases is not passing. I tried running test without making any changes to original repository and it didn't pass there either. 
I am pretty new to this so it would be nice to get some pointers.

Screenshot of the problem:-
![Screenshot from 2019-10-21 02-31-33](https://user-images.githubusercontent.com/25086429/67166370-40e22e00-f3ac-11e9-92ac-161dba4f6d1d.png)

**Comment by vorillaz** [comment]
@eElec Hello, try to run `yarn && yarn bootstrap ` after adding your package. This will allow Lerna to access all internal packages. For snapshot testing use `yarn test -u `

**Comment by ColinFrick** [comment]
```js
isEmpty(' ');
// => true
```

Shouldn't this be false? IMHO a white space should not be considered an empty string. Renaming this to isBlank would clear any confusion, and align it with other string utilities (like StringUtils in Java)

**Comment by vorillaz** [comment]
@ColinFrick You are not actually right, considering a string with whitespaces is empty.
