### ISSUE TITLE
Feature request: `isAlphaDigit`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#20]
Checks whether the input text contains only alpha and digit characters.

**Example usage**

```javascript
import isAlphaDigit from '@plexis/is-alphadigit';

isAlphaDigit('ABCD');
// => true

isAlphaDigit('Apollo11');
// => true

isEmpty('Hello world');
// => false

isEmpty('Hello,world');
// => false

isAlphaDigit('');
// => false

isEmpty('   ');
// => false
```

**Aliases**

```javascript
import isAlphaDigit from '@plexis/is-alphadigit';
import {isAlphaDigit} from 'plexis';
```

**Comment by floookay** [comment]
@vorillaz Hi, I'd like to work on this issue. If you agree I'd like to rename this feature to `isAlphanumeric` or `isAlphaNumeric`. What do you think?

**Comment by vorillaz** [comment]
@floookay Sure thing, you also use an alias as well. Thanks for the contribution mate!
