### ISSUE TITLE
Feature request: `isAlpha`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#21]
Checks whether the input text contains only alpha characters.

**Example usage**

```javascript
import isAlpha from '@plexis/is-alpha';

isAlpha('ABCD');
// => true

isAlpha('Apollo11');
// => false

isEmpty('1');
// => false

isEmpty('Hello,world');
// => false

isAlpha('');
// => false

isEmpty('   ');
// => false
```

**Aliases**

```javascript
import isAlpha from '@plexis/is-alpha';
import {isAlpha} from 'plexis';
```

**Comment by RobFairclough** [comment]
Love this idea, I'll give it a shot!

**Comment by vorillaz** [comment]
@RobFairclough 💪 Let's do this!

**Comment by ThakurKarthik** [comment]
@RobFairclough are you working on this?

**Comment by RobFairclough** [comment]
@ThakurKarthik Yes, pull request here https://github.com/plexis-js/plexis/pull/28 - just waiting for re-review after some version/alphabetising changes.

**Comment by vorillaz** [comment]
@RobFairclough The PR was merged, thanks :)
