### ISSUE TITLE
Feature request: `toPlural`

### ISSUE THREAD

**Issue by APZelos** [plexis-js/plexis#31]
Converts the input text to its plural form.
Optional param: Count.
Optional param: Custom plural form (must also provide a count).

**Example usage**
```js
import toPlural from '@plexis/to-plural';

toPlural('example');
// => 'examples';

toPlural('example', 10);
// => 'examples';

toPlural('example', 1);
// => 'example';

toPlural('example', 'examplez', 10);
// => 'examplez';

toPlural('example', 'examplez', 1);
// => 'example';
```
**Aliases**
```js
import toPlural from '@plexis/to-plural';
import {toPlural, pluralize} from 'plexis';
```

**Comment by vorillaz** [comment]
@APZelos I would suggest using an extra alias, maybe `pluralize`.

**Comment by APZelos** [comment]
Yes `pluralize` sounds good!

**Comment by shilangyu** [comment]
Im willing to implement it, could you assign it to me? thanks :)

**Comment by vorillaz** [comment]
@shilangyu Done!

**Comment by shilangyu** [comment]
Should it do some context analysis? or simple "add an 's'" will suffice?

**Comment by shilangyu** [comment]
I see currently no package throws an error:

> Optional param: Custom plural form (must also provide a count).

How should I handle a case where a count isnt provided? Can i throw an error?

**Comment by vorillaz** [comment]
@shilangyu We can assume that the count is `1`

**Comment by shilangyu** [comment]
Done!
