### ISSUE TITLE
Feature request:  `toTurabian/ toChicagoManualStyle/ toChicagoStyle`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#4]
A method that transforms text according to [Turabian / Chicago Style](https://cmosshoptalk.com/2018/11/13/how-do-i-format-main-text-in-turabian-chicago-style/) format.

```javascript
@param {String} [txt] The text to transform
@returns {String} Returns text transformed according to the The Chicago Manual of Style.
```

**Example usage**

```javascript
import toChicago from '@plexis/to-chicago';
toChicago('This is a title'); // returns 'This Is a Title'
toChicago('in Turabian shows a sample title page for a class paper.'); // returns 'In Turabian Shows a Sample Title Page for a Class Paper.'
toChicago('camelCase PascalCase snake_case and kebab-case'); // returns 'Camelcase Pascalcase Snake_case and Kebab-Case'
```

**Aliases**

```javascript
import toChicago from '@plexis/to-chicago';
import {toTurabian, toChicagoManualStyle, toChicagoStyle, toChicagoTitle } from 'plexis'
```

**Comment by dungwinux** [comment]
@vorillaz, may I take this ?

**Comment by vorillaz** [comment]
@dungwinux Go for it!

**Comment by dungwinux** [comment]
@vorillaz. Just want to make sure, is reference link correct ? The test cases you give don't seem to match the Chicago style mentioned in the link.

**Comment by vorillaz** [comment]
@dungwinux The Chicago Manual of Style has lots of resources and online about text formatting.
You can also take a look at these references / online tools:
- https://title.sh/
- https://capitalizemytitle.com/
- https://libanswers.snhu.edu/faq/135231
