### ISSUE TITLE
Feature: `toSwapCase / swapCase`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#74]
Swaps lowercase to uppercase and vice versa for the input text.

**Example usage**

```javascript
import toSwapCase from '@plexis/to-swap-case';

toSwapCase('Hello WORLD');
// => 'hELLO world'

toSwapCase('123 toys');
// => '123 toys'

```

**Aliases**

```javascript
import toSwapCase from '@plexis/to-swap-case';
import {toSwapCase, swapCase} from 'plexis';
```

**Comment by Tobenna-KA** [comment]
So we dont swap cases if string starts with anything other than a letter?

**Comment by vorillaz** [comment]
@Tobenna-KA You can just ignore everything that's not a letter.

**Comment by nowtryz** [comment]
This is a good one, brainstorm time!

**Comment by Tobenna-KA** [comment]
cool, shouldn't take long

**Comment by vorillaz** [comment]
@Tobenna-KA @nowtryz Pull requests are welcome, also if you want any additional feedback or guideline you can take a look at the documentation or even ping me directly.

**Comment by nowtryz** [comment]
It is for all char isn't it ? like all of [these](https://en.wikipedia.org/wiki/Latin_script_in_Unicode) ?

**Comment by vorillaz** [comment]
> It is for all char isn't it ? like all of [these](https://en.wikipedia.org/wiki/Latin_script_in_Unicode) ?

@nowtryz Yeap :) _Hint:_ instead of matching any single character of all alphabets you can use a regular expression to detect symbols ;)

**Comment by nowtryz** [comment]
Yeah, I'm on a good way I think, can I have a complex string to test, please?
