### ISSUE TITLE
Feature: `toSwap / swap`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#75]
Swaps every single character with the next one in a given string.

**Example usage**

```javascript
import toSwap from '@plexis/to-swap';

toSwap('ab');
// => 'ba'

toSwap('a b');
// => ' ab'

toSwap('abcd');
// => 'badc'

```

**Aliases**

```javascript
import toSwap from '@plexis/to-swap';
import {toSwap, swap} from 'plexis';
```

**Comment by drwm-base** [comment]
Hi! I would like to work on this issue.

**Comment by vorillaz** [comment]
@drwm-base Go for it!

**Comment by drwm-base** [comment]
So the function would swap every character with the next one in the string? Like
abc => bca

**Comment by drwm-base** [comment]
Also this is my first time contributing to this project, do I just add the function to the packages folder like the others?

**Comment by vorillaz** [comment]
> So the function would swap every character with the next one in the string? Like
> abc => bca

Nope, thats reversing the input. Just swap any case with the next one, if there no other characters left do nothing
```
abc => bac
abcd => badc
ab cd => bac d
```

> Also this is my first time contributing to this project, do I just add the function to the packages folder like the others?
> 
> EDIT: Nevermind, needed to look at the README more carefully, sorry


No worries :).

**Comment by drwm-base** [comment]
Hey so I ran lerna create, but it created a different format than the other packages. Is this incorrect?

**Comment by vorillaz** [comment]
@drwm-base It needs a bit manually tweaking, there is an example in the `.template` folder.

**Comment by drwm-base** [comment]
thanks

**Comment by drwm-base** [comment]
Hey vorillaz, I dont understand why the first case is not 'ab' becomes 'ba'? Unless you want me to ignore strings of length 2?

**Comment by vorillaz** [comment]
@drwm-base You are right, I updated the issue.

**Comment by drwm-base** [comment]
Thanks, also its almost done. I look forward to contributing to this project more, I've learned a lot here already and I really like what you guys are doing!

**Comment by vorillaz** [comment]
@drwm-base I am really glad that you liked it. Keep up the good work :D

**Comment by drwm-base** [comment]
Hey so my tests run and pass, but I cant commit as husky doesn't like my version of nodejs. At least I think so. Also do I have to update package.json for plexis folder manually when I'm done adding the new package?

**Comment by vorillaz** [comment]
@drwm-base Yes please, add the new package to `plexis/package.json` and run `yarn bootstrap`. I don't think that husky is relative to your node version. Maybe you have to adjust your commit message for commitlint?

**Comment by drwm-base** [comment]
Ahhh maybe.... Thanks for the help! I also need to add it to plexis/src/index.js right? As an export? Or is that done automatically?

**Comment by drwm-base** [comment]
So I'm done. I just cant get all the tests to run as I keep getting this error:

Cannot find module '@plexis/to-swap' from 'index.js'. Do I need to add anything else? I've already added toSwap to index.js and package.json in plexis?
