### ISSUE TITLE
Feature request: `toCapitals / toFirstCapital / capitalize`

### ISSUE THREAD

**Issue by vorillaz** [plexis-js/plexis#8]
Converts the first character of the input text to upper case. If the second parameter is true, the method converts the rest of the subject to lower case.

```javascript
  @param {String} text
  @param {Boolean} isLowercase
```

**Example usage**

```javascript
import toCapitals from '@plexis/to-capitals';
toCapitals('foo Bar');
// => Foo Bar

toCapitals('fOO Bar');
// => FOO Bar

toCapitals('fOO Bar', true);
// => Foo bar
```

**Aliases**

```javascript
import toCapitals from '@plexis/to-capitals';
import {toCapitals, toFirstCapital, capitalize} from 'plexis';
```

**Comment by rajeshwarKrr** [comment]
can I work on this part of plexis

**Comment by vorillaz** [comment]
@rajeshwarKrr Sure!

**Comment by AngelGzS** [comment]
> can I work on this part of plexis

Are you working in this feature? @rajeshwarKrr

**Comment by rajeshwarKrr** [comment]
@AngelGzS  U please go with it 

I will be busy for next couple of days
